ansible_become: yes

medifor_dir: /opt/medifor
config_file_dir: /opt/medifor
medifor_ui_docker_tag: develop
analytic_worker_tag: develop
medifor_demo_data_dir: /medifor_demo_data
container_data_dir: /medifor_demo_data
medifor_backup_dir: /medifor_backup
workflow_host: "analytic_workflow"
workflow_port: "50051"
medifor_ui_port: 3000
medifor_defaultFuserId: "ta2-combo"
env: "production"

include_ui: true
include_gt: true

medifor_ui_enableGroups: false
medifor_ui_enableDelete: true
medifor_ui_unknownUsers: deny
medifor_ui_groupPrefix: medifor-uigrp-
medifor_ui_groupTagPrefix: group
medifor_ui_userTagPrefix: user
medifor_ui_tagPrefixFlag: __
medifor_ui_cache_seconds: 20

containers:
  image:
    - id: ela
      name: Error Level Analysis
      description: Identifying areas within an image that are at different compression levels
      container: gitlab-registry.mediforprogram.com/medifor/program-registry/nextcentury_s_ela-base:2019-11-14T17-17-26f378000
    - id: exif
      name: Baseline Analytic Exif
      description: Retrive Exif Data
      container: gitlab-registry.mediforprogram.com/medifor/program-registry/medifor_s_baseline-analytic-exif:prod2020-03
  fusion:
    - id: ta2avg
      name: Image Averaging Fusion
      description: Averages all analytic input scores available to calculate score
      container: gitlab-registry.mediforprogram.com/medifor/program-registry/nextcentury_s_fusion-container:2019-12-12T19-54-07f733000
      handles: ["image"]
