ansible_become: yes

medifor_dir: ../server/config
config_file_dir: ../pipeline/config
medifor_ui_docker_tag: latest
analytic_worker_tag: latest
medifor_demo_data_dir: /tmp/analyticsui
container_data_dir: /medifor
medifor_backup_dir: /medifor_backup
workflow_host: "analytic_workflow"
workflow_port: "50051"
medifor_ui_port: 3000
medifor_defaultFuserId: "ta2avg"
env: "production"

include_ui: true
include_gt: true

medifor_ui_enableGroups: false
medifor_ui_enableDelete: true
medifor_ui_unknownUsers: deny
medifor_ui_groupPrefix: medifor-uigrp-
medifor_ui_groupTagPrefix: group
medifor_ui_userTagPrefix: user
medifor_ui_tagPrefixFlag: __
medifor_ui_cache_seconds: 20

containers:
  image:
    - id: ela
      name: Error Level Analysis
      description: Identifying areas within an image that are at different compression levels
      container: docker.pkg.github.com/mediaforensics/packages/ela:latest
    - id: exif
      name: Baseline Analytic Exif
      description: Retrive Exif Data
      container: docker.pkg.github.com/mediaforensics/packages/exif:latest
  fusion:
    - id: ta2avg
      name: Image Averaging Fusion
      description: Averages all analytic input scores available to calculate score
      container: docker.pkg.github.com/mediaforensics/packages/ta2avg:latest
      handles: ["image"]
