import Vue from "vue";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  FontAwesomeIcon,
  FontAwesomeLayers
} from "@fortawesome/vue-fontawesome";

import {
  faAngleDown,
  faBackward,
  faBars,
  faBookmark,
  faCamera,
  faCaretDown,
  faCaretRight,
  faCaretUp,
  faChartBar,
  faCheckCircle,
  faCheckSquare,
  faChevronLeft,
  faChevronRight,
  faCloudUploadAlt,
  faCog,
  faDownload,
  faEdit,
  faExclamationCircle,
  faExpand,
  faFileCode,
  faFileCsv,
  faFilePdf,
  faFileUpload,
  faFilter,
  faFont,
  faForward,
  faImage,
  faInfoCircle,
  faList,
  faMinus,
  faMinusCircle,
  faPause,
  faPauseCircle,
  faPen,
  faPhotoVideo,
  faPlay,
  faPlayCircle,
  faPlus,
  faPlusCircle,
  faRedo,
  faSearch,
  faSpinner,
  faStream,
  faSync,
  faTag,
  faTh,
  faTimes,
  faTrashAlt,
  faUndo,
  faUpload,
  faVideo,
  faVolumeMute,
  faVolumeUp
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAngleDown,
  faBackward,
  faBars,
  faBookmark,
  faCamera,
  faCaretDown,
  faCaretRight,
  faCaretUp,
  faChartBar,
  faCheckCircle,
  faCheckSquare,
  faChevronLeft,
  faChevronRight,
  faCloudUploadAlt,
  faCog,
  faDownload,
  faEdit,
  faExclamationCircle,
  faExpand,
  faFileCode,
  faFileCsv,
  faFilePdf,
  faFileUpload,
  faFilter,
  faFont,
  faForward,
  faImage,
  faInfoCircle,
  faList,
  faMinus,
  faMinusCircle,
  faPause,
  faPauseCircle,
  faPen,
  faPhotoVideo,
  faPlay,
  faPlayCircle,
  faPlus,
  faPlusCircle,
  faRedo,
  faSearch,
  faSpinner,
  faStream,
  faSync,
  faTag,
  faTh,
  faTimes,
  faTrashAlt,
  faUndo,
  faUpload,
  faVideo,
  faVolumeMute,
  faVolumeUp
);

Vue.component("font-awesome-icon", FontAwesomeIcon);
Vue.component("font-awesome-layers", FontAwesomeLayers);
