# Ansible managed
version: "2"

networks:
  mfnet:

services:
  pgmedifor:
    image: "postgres:11"
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata 
    networks:
      - mfnet
    ports:
      - "5432:5432"
    volumes:
      - "${MEDIFOR_DEMO_DATA_DIR}/pgsql:/var/lib/postgresql/data"

  eqmedifor:
    image: "shiblon/entroq:v0.2"
    restart: always
    command:
      - "pg"
      - "--dbaddr=pgmedifor:5432"
      - "--attempts=10"
    networks:
      - mfnet

  analytic_workflow:
    image: "docker.pkg.github.com/mediaforensics/packages/analyticworker:latest"
    restart: always
    command:
      - "analyticworkflow"
      - "--pgaddr=pgmedifor:5432"
      - "--eqaddr=eqmedifor:37706"
      - "--analytic_config=/analytic_config.json"
      - "--listen=:50051"
    volumes :
      - ../pipeline/config/analytic_config.json:/analytic_config.json
    networks:
      - mfnet
    ports:
      - "50051:50051"

  medifor_ui:
    image: "docker.pkg.github.com/mediaforensics/packages/medifor-ui:latest"
    restart: always
    networks:
      - mfnet
    environment:
      - CONTAINER_ROOT=${CONTAINER_DATA_DIR}
      - WORKFLOW_HOST=${WORKFLOW_HOST}
      - WORKFLOW_PORT=${WORKFLOW_PORT}
    volumes:
      - "${MEDIFOR_DEMO_DATA_DIR}:${CONTAINER_DATA_DIR}"
      - ../server/config/development.json:/usr/src/app/config/production.json
    ports:
      - "3000:3000"

  
# === Analytic Containers ===
# Containers for image

  ac_ela:
    image: docker.pkg.github.com/mediaforensics/packages/ela:latest
    restart: "always"
    networks:
      - mfnet
    volumes:
      - "${MEDIFOR_DEMO_DATA_DIR}/input:${CONTAINER_DATA_DIR}/input"
      - "${MEDIFOR_DEMO_DATA_DIR}/output:${CONTAINER_DATA_DIR}/output"
  aw_ela:
    image: "docker.pkg.github.com/mediaforensics/packages/analyticworker:${ANALYTIC_WORKER_TAG}"
    restart: always
    command:
      - "analyticworker"
      - "--eqaddr=eqmedifor:37706"
      - "--backend=ac_ela:50051"
      - "--id=ela"
    networks:
      - mfnet
  ac_exif:
    image: docker.pkg.github.com/mediaforensics/packages/exif:latest
    restart: "always"
    networks:
      - mfnet
    volumes:
      - "${MEDIFOR_DEMO_DATA_DIR}/input:${CONTAINER_DATA_DIR}/input"
      - "${MEDIFOR_DEMO_DATA_DIR}/output:${CONTAINER_DATA_DIR}/output"
  aw_exif:
    image: "docker.pkg.github.com/mediaforensics/packages/analyticworker:${ANALYTIC_WORKER_TAG}"
    restart: always
    command:
      - "analyticworker"
      - "--eqaddr=eqmedifor:37706"
      - "--backend=ac_exif:50051"
      - "--id=exif"
    networks:
      - mfnet

# Containers for fusion

  ac_ta2avg:
    image: docker.pkg.github.com/mediaforensics/packages/ta2avg:latest
    restart: "always"
    networks:
      - mfnet
    volumes:
      - "${MEDIFOR_DEMO_DATA_DIR}/input:${CONTAINER_DATA_DIR}/input"
      - "${MEDIFOR_DEMO_DATA_DIR}/output:${CONTAINER_DATA_DIR}/output"
  aw_ta2avg:
    image: "docker.pkg.github.com/mediaforensics/packages/analyticworker:${ANALYTIC_WORKER_TAG}"
    restart: always
    command:
      - "fusionworker"
      - "--eqaddr=eqmedifor:37706"
      - "--backend=ac_ta2avg:50051"
      - "--id=ta2avg"
    networks:
      - mfnet

